### ISSUE TITLE
flowcell_unmapped_bams_list not listed in inputs

### ISSUE THREAD

**Issue by kdbinder** [gatk-workflows/broad-prod-wgs-germline-snps-indels#13]
In the new "fc" version, the wdl references "File flowcell_unmapped_bams_list" however the corresponding inputs file still references the older "flowcell_unmapped_bams"

**Comment by bshifaw** [comment]
Hi @kdbinder ,

The Paired Single Sample input json file currently available works for [PairedEndSingleSampleWf.wdl](https://github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels/blob/master/PairedEndSingleSampleWf.wdl) not the fc version. This is because there were some modifications made to the fc version to make it more user friendly on Firecloud like supplying a list of ubams.  If you would like to get an the example data used to run the workflow please visit the featured workspace [PairedEndSingleSampleWf-Firecloud-HG38](https://portal.firecloud.org/#workspaces/help-gatk/Pre-processing_hg38_v2/method-configs/gatk/PairedEndSingleSampleWf-Firecloud-HG38).

Hint: it is gs://gatk-test-data/wgs_ubam/NA12878_24RG/NA12878_24RG_small.txt

**Comment by kdbinder** [comment]
Thanks @bshifaw 

Is the non-fc version using GATK 4 (as the changes indicate "replaced gatk4 version of single sample with fc version")?

**Comment by bshifaw** [comment]
The gatk4 that non-fc wdl uses is from the gitc docker while gatk4 the fc version wdl uses is from gatk docker. This makes it easier to change the gatk4 docker image being used in FC

**Comment by bshifaw** [comment]
FYI: 
GITC stands for genome-in-the-cloud which is a docker container that contains a few useful bioinformatics tools listed [here](https://hub.docker.com/r/broadinstitute/genomes-in-the-cloud). Though convient the problem with listing several tools in a single docker image is having to constantly create new releases of the image so that the tools inside are using the latest version. GATK is routinely updated so its easier to use its particular docker image [here](https://hub.docker.com/r/broadinstitute/gatk).
FC stands for [FireCloud](https://software.broadinstitute.org/firecloud/) "An open platform for secure and scalable analysis on the cloud". FC can use json files to run the wdl workflows but the ideal process for running workflows uses a table listing paths to the data called a Data Model. The fc version has been edited in away to easily work with the Data Model.

**Comment by bshifaw** [comment]
Feel free to take advantage of our forums [GATK](https://gatkforums.broadinstitute.org/gatk/categories/ask-the-team/) , [FireCloud](https://gatkforums.broadinstitute.org/firecloud/categories/ask-the-firecloud-team) or [Terra](https://broadinstitute.zendesk.com/hc/en-us/community/topics/360000500432-General-Discussion) , [WDL/Cromwell](https://gatkforums.broadinstitute.org/wdl/categories/ask-the-wdl-team).
